spring.profiles.include: diag

environment:
    discoveryLocations: https://localhost:10011/eureka/
    dsIpAddress: 0.0.0.0
    esmEnabled: false
    eurekaPassword: password
    eurekaUserId: eureka
    gatewayHostname: https://localhost:10010
    hostname: localhost
    ipAddress: 127.0.0.1
    port: 10012
    preferIpAddress: false
    truststore: keystore/localhost/localhost.truststore.p12
    truststorePassword: password
    truststoreType: PKCS12

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseExpirationDurationInSeconds: 6
        leaseRenewalIntervalInSeconds: 5

server:
    ssl:
        enabled: true
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12

mfaas:
    service-registry:
        cacheRefreshInitialDelayInMillis: 10000
        cacheRefreshRetryDelayInMillis: 10000
        cacheRefreshUpdateThresholdInMillis: 120000
        serviceFetchDelayInMillis: 10000

apiml:
    banner: console
    enabled: true
    service:
        serviceId: apicatalog
        title: Zowe APIML Catalog #©     #Copyright is for UTF8 encoding check
        description:  Zowe API Mediation Layer Catalog service
        hostname: localhost
        ipAddress: 127.0.0.1
        scheme: https
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${server.port}
        homePageRelativeUrl: ${server.servlet.contextPath}
        statusPageRelativeUrl: actuator/info
        healthCheckRelativeUrl: actuator/health
        serviceIpAddress: 127.0.0.1

        discoveryServiceUrls: https://localhost:10011/eureka/

        apiInfo:
            -   apiId: org.zowe.discoverableclient
                gatewayUrl: api/v1
                version: 1.0.0
                swaggerUrl: https://${apiml.service.hostname}:${server.port}${server.servlet.contextPath}/v1/api-docs
                documentationUrl: https://www.zowe.org
        routes:
            -   gatewayUrl: ui/v1
                serviceUrl: ${server.servlet.contextPath}
            -   gatewayUrl: api/v1
                serviceUrl: ${server.servlet.contextPath}/api/v1
            -   gatewayUrl: ws/v1
                serviceUrl: ${server.servlet.contextPath}/ws
        catalog:
            tile:
                id: catalog
                title: API Mediation Layer Services
                description: Zowe API Mediation Layer services
                version: 1.0.0
        security:
            ssl:
                ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
                verifySslCertificatesOfServices: true
                protocol: TLSv1.2
                keyAlias: localhost
                keyPassword: password
                keyStore: keystore/localhost/localhost.keystore.p12
                keyStorePassword: password
                keyStoreType: PKCS12
                trustStore: keystore/localhost/localhost.truststore.p12
                trustStorePassword: password
                trustStoreType: PKCS12

spring:
    output:
        ansi:
            enabled: always
