spring:
    profiles:
        include: diag
    output:
        ansi:
            enabled: always

eureka:
    client:
        serviceUrl:
            defaultZone: ${apiml.service.discoveryServiceUrls}
