spring.profiles.include: diag
logging:
    level:
        com.ca.mfaas.client: DEBUG
        com.ca.mfaas.security: DEBUG

#spring:
#    output:
#        ansi:
#            enabled: always

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password

apiml:
    enabled: true

    service:
        serviceIpAddress: 127.0.0.1
        discoveryServiceUrls: https://localhost:10011/eureka/

        scheme: https
        #baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}

        ssl:
            enabled: false
            verifySslCertificatesOfServices: false
            keyAlias: localhost
            keyPassword: password
            keyStore: keystore/localhost/localhost.keystore.p12
            keyStorePassword: password
            trustStore: keystore/localhost/localhost.truststore.p12
            trustStorePassword: password

eureka:
    client:
        serviceUrl:
            defaultZone: ${apiml.service.discoveryServiceUrls}
