spring.profiles.include: diag

server:
    ssl:
        enabled-protocols: ${apiml.service.ssl.protocol} #TLSv1.2

        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10012
        scheme: https
        # serviceIpAddress: ${apiml.service.ipAddress} #127.0.0.1
        discoveryServiceUrls: https://localhost:10011/eureka/
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}

        #ssl:
        #    keyAlias: localhost
        #    keyPassword: password
        #    keyStore: keystore/localhost/localhost.keystore.p12
        #    keyStorePassword: password
        #    trustStore: keystore/localhost/localhost.truststore.p12
        #    trustStorePassword: password
spring:
    output:
        ansi:
            enabled: always


eureka:
    client:
        serviceUrl:
            defaultZone: ${apiml.service.discoveryServiceUrls}
