spring.profiles.include: diag

spring:
    output:
        ansi:
            enabled: always

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12
    servlet:
        contextPath: #/gateway

apiml:
    enabled: true
    banner: console

    service:
        hostname: localhost
        port: 10010
        serviceId: gateway
        title: Zowe APIML Gateway #©     #Copyright is for UTF8 encoding check
        description:  Zowe API Mediation Layer Gateway service
        scheme: https
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${server.port}
        homePageRelativeUrl: ${server.servlet.contextPath}
        statusPageRelativeUrl: actuator/info
        healthCheckRelativeUrl: actuator/health
        serviceIpAddress: 127.0.0.1

        discoveryServiceUrls: https://localhost:10011/eureka/

        apiInfo:
            -   apiId: org.zowe.apiml.gateway
                gatewayUrl: api/v1
                version: 1.0.0
                swaggerUrl: https://${apiml.service.hostname}:${server.port}${server.servlet.contextPath}/v1/api-docs
                documentationUrl: https://www.zowe.org
        routes:
            -   gatewayUrl: ui/v1
                serviceUrl: ${server.servlet.contextPath}
            -   gatewayUrl: api/v1
                serviceUrl: ${server.servlet.contextPath}/api/v1
            -   gatewayUrl: ws/v1
                serviceUrl: ${server.servlet.contextPath}/ws
        catalog:
            tile:
                id: apiml
                title: API Mediation Layer Services
                description: Zowe API Mediation Layer services
                version: 1.0.0
    security:
        auth:
            provider: dummy
            zosmfServiceId: zosmf  # Replace me with the correct z/OSMF service id
        ssl:
            ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
            verifySslCertificatesOfServices: true
            protocol: TLSv1.2
            keyAlias: localhost
            keyPassword: password
            keyStore: keystore/localhost/localhost.keystore.p12
            keyStorePassword: password
            keyStoreType: PKCS12
            trustStore: keystore/localhost/localhost.truststore.p12
            trustStorePassword: password
            trustStoreType: PKCS12
